---
- name: Install local ansible data path directory (local)
  tags: liferay
  local_action: file
    state=directory
    owner=0
    group=0
    mode=2777
    dest={{ local_ansible_data_path }}

- name: Download Tomcat bundle (local)
  tags: liferay
  sudo: no
  local_action: get_url
    dest={{ local_ansible_data_path }}/{{ liferay_bundle_archive }}
    url={{ liferay_download_base_url }}/{{ liferay_bundle_archive }}
    mode=0644
    sha256sum={{ liferay_bundle_archive_shasum }}

- name: Download MySQL connector (local)
  tags: liferay
  sudo: no
  local_action: get_url
    dest={{ local_ansible_data_path }}/{{ mysql_connector_archive }}
    url={{ mysql_connector_download_base_url }}/{{ mysql_connector_archive }}
    mode=0644
    sha256sum={{ mysql_connector_archive_shasum }}
